function(sanitize_value_for_filename VALUE OUTPUT)
  string(REPLACE " " "_" SANITIZED ${VALUE})
  string(REPLACE ":" "_" SANITIZED ${SANITIZED})
  set(${OUTPUT} "${SANITIZED}" PARENT_SCOPE)
endfunction()

function(prepare_filename VALUES TOKEN FILENAME OUTPUT)
  set(I 0)
  set(${OUTPUT} ${FILENAME})
  foreach( VALUE IN LISTS VALUES )
    sanitize_value_for_filename( ${VALUE} VALUE_OK )
    set(TOKEN_FOR_VALUE "${TOKEN}${I}")
    string(REPLACE ${TOKEN_FOR_VALUE} ${VALUE_OK} ${OUTPUT} ${${OUTPUT}})
    math(EXPR I "${I}+1")
  endforeach()
  set(${OUTPUT} "${${OUTPUT}}" PARENT_SCOPE)
endfunction()

function(INSTANTIATE_CPP SRCS)
  set(oneValueArgs LEVELS)
  set(multiValueArgs TARGETS VALUES)
  cmake_parse_arguments(instantiate_cpp "" "${oneValueArgs}" "${multiValueArgs}" ${ARGN})
  if (NOT instantiate_cpp_LEVELS)
    set(instantiate_cpp_LEVELS 1)
  endif()

  foreach(_file ${instantiate_cpp_TARGETS})
    foreach(_value0 ${instantiate_cpp_VALUES})
      set(values "")
      list(APPEND values ${_value0})
      if (${instantiate_cpp_LEVELS} EQUAL 1)
        prepare_filename( ${values} instance ${_file} FILENAME )
        list(APPEND ${SRCS} ${FILENAME})
        set(VALUE0 ${_value0})
        configure_file(${_file} ${FILENAME} @ONLY) 
      elseif (${instantiate_cpp_LEVELS} EQUAL 2)
        foreach(_value1 ${instantiate_cpp_VALUES})
          list(APPEND values ${_value1})
          prepare_filename( "${values}" instance ${_file} FILENAME )
          list(APPEND ${SRCS} ${FILENAME})
          set(VALUE0 ${_value0})
          set(VALUE1 ${_value1})
          configure_file(${_file} ${FILENAME} @ONLY) 
          list(POP_BACK values)
        endforeach()
      endif()
    endforeach()
  endforeach()
  set(${SRCS} ${${SRCS}} PARENT_SCOPE)
endfunction()


